service: login-regservice
plugins:
  - serverless-offline
  - serverless-prune-plugin

custom:
  config: ${file(./config.${self:provider.stage}.json)}
  stageFlag: ${self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.config.lambdaRegion}
  role: ${self:custom.config.lambdaRole}
  endpointType: REGIONAL
  environment:
    NODE_ENV: ${self:provider.stage}
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6

functions:
  loginregservice: 
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

